import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from './components/Header/Header'
import './globals.css'
import Footer from './components/Footer/Footer'

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '300', '400'],
	variable: '--font-poppins',
})

export const metadata: Metadata = {
	title: 'Portfolio',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
